version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    privileged: true
    deploy:
      restart_policy:
        condition: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: carwash
      MYSQL_USER: admin
      MYSQL_PASSWORD: "123"
    ports:
      - "3306:3306"
    command: --sql_mode="" --general-log=1 --general-log-file=/var/lib/mysql/general.log --slow-query-log=1 --slow-query-log-file=/var/lib/mysql/slow.log --long_query_time=1 --log-queries-not-using-indexes